name: "Raspberry Pi Sysroot"
description: "Prepare Raspberry Pi sysroot"

inputs:
  version:
    description: "Raspbian distro version"
    default: "bullseye"
    required: false
  path:
    description: "Location of sysroot"
    default: "/opt/pi-sysroot"
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache sysroot
      uses: actions/cache@v2
      id: sysroot-cache
      with:
        path: |
          /opt/pi-sysroot/bin
          /opt/pi-sysroot/lib
          /opt/pi-sysroot/opt
          /opt/pi-sysroot/usr
        key: ${{ runner.os }}-${{ inputs.version }}-${{ hashFiles('./scripts/raspi/pi-sysroot-setup.sh') }}

    - name: Update packages
      shell: bash
      run: sudo apt-get -qq update || true

    - name: Install Required Build Tools
      shell: bash
      # Use qemu to support cross-architecture debootstrap
      run: sudo apt-get -y -qq install crossbuild-essential-armhf cmake gettext

    - name: Install Sysroot
      if: steps.sysroot-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get -y -qq install debootstrap qemu-user-static
        sudo update-binfmts --enable qemu-arm
        sudo mkdir -p ${{ inputs.path }}
        sudo debootstrap --arch=armhf --no-check-gpg bullseye ${{ inputs.path }} http://raspbian.raspberrypi.org/raspbian/
        sudo RELEASE=${{ inputs.version }} chroot ${{ inputs.path }} bash < ${{github.workspace}}/scripts/raspi/pi-sysroot-setup.sh