name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*.*.*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  release-webos:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install webOS CLI
        run: sudo npm install -g @webosose/ares-cli

      - name: Install Dev Dependency
        run: npm install

      - name: Install Required Build Tools
        run: sudo apt-get -y -qq install cmake

      - name: Download webOS NDK
        run: wget -q https://github.com/webosbrew/meta-lg-webos-ndk/releases/download/1.0.g-rev.4/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -P ${{github.workspace}}/temp

      - name: Install webOS NDK
        run: chmod 755 ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh && sudo ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -y

      - name: Initialize NDK Environments
        run: env -i bash -c '. /opt/webos-sdk-x86_64/1.0.g/environment-setup-armv7a-neon-webos-linux-gnueabi && env' >> $GITHUB_ENV

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTARGET_WEBOS=ON -DCMAKE_TOOLCHAIN_FILE=/opt/webos-sdk-x86_64/1.0.g/sysroots/x86_64-webossdk-linux/usr/share/cmake/OEToolchainConfig.cmake

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE --target webos-package-moonlight

      - name: Set Environment for Release
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cat github-release.env >> $GITHUB_ENV

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE

      - name: Create Release (webOS)
        id: create_release_webos
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.tagName.outputs.tag }}
          prerelease: true
          allowUpdates: true
          artifacts: build/${{ env.RELEASE_IPK_FILENAME }},build/${{env.RELEASE_MANIFEST_FILENAME}}

  release-raspi:
    runs-on: ubuntu-latest
    env:
      SYSROOT: "/opt/pi-sysroot"
      RASPBIAN_VERSION: "bullseye"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Cache sysroot
        uses: actions/cache@v2
        id: sysroot-cache
        with:
          path: |
            /opt/pi-sysroot/bin
            /opt/pi-sysroot/lib
            /opt/pi-sysroot/opt
            /opt/pi-sysroot/usr
          key: ${{ runner.os }}-${{ env.RASPBIAN_VERSION }}-${{ hashFiles('./scripts/raspi/pi-sysroot-setup.sh') }}

      - name: Update packages
        run: sudo apt-get -qq update || true

      - name: Install Required Build Tools
        # Use qemu to support cross-architecture debootstrap
        run: sudo apt-get -y -qq install crossbuild-essential-armhf cmake gettext

      - name: Install Sysroot
        if: steps.sysroot-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get -y -qq install debootstrap qemu-user-static
          sudo update-binfmts --enable qemu-arm
          sudo mkdir -p ${SYSROOT}
          sudo debootstrap --arch=armhf --no-check-gpg bullseye ${SYSROOT} http://raspbian.raspberrypi.org/raspbian/
          sudo RELEASE=${RASPBIAN_VERSION} chroot ${SYSROOT} bash < ${{github.workspace}}/scripts/raspi/pi-sysroot-setup.sh

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTARGET_RASPI=ON -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/scripts/raspi/PiCrossToolchain.cmake

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE

      - name: Package
        working-directory: ${{github.workspace}}/build
        run: |
          cpack
          dpkg-scanpackages . > Release

      - name: Create Release (Raspberry Pi)
        id: create_release_raspi
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.tagName.outputs.tag }}
          prerelease: true
          allowUpdates: true
          artifacts: build/*.deb,build/Release
